// Regenerates the "State Program Packs (audit trail)" section of docs/sources.md
// from the actual program data. Run: npm run audit:sources
//
// Why a script: the audit trail is the project's evidence that every shipped
// figure came from a named official source on a named date. Hand-maintaining
// that table alongside 11 (eventually 50) state packs guarantees drift, and a
// drifted audit trail is worse than none. The volatile watch-list is derived
// from each program's `volatile` field, so the warning always travels with the
// number it's about.
//
// Only the region between the two markers below is rewritten — the rest of
// docs/sources.md is hand-written and must never be clobbered.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DOC = "docs/sources.md";
const START = "<!-- BEGIN:state-packs (generated by scripts/audit-sources.mjs — do not edit) -->";
const END = "<!-- END:state-packs -->";
const STATES_DIR = "src/data/states";

const CATEGORY_LABEL = {
  food: "Food",
  health: "Health",
  energy: "Energy",
  cash: "Cash",
  education: "Education",
  housing: "Housing",
  tax: "Tax",
  "phone-internet": "Phone & Internet",
};

/**
 * Read the ordered list of promoted state codes straight out of deep.ts, so the
 * doc can never claim a state the app doesn't actually ship.
 */
function deepStateCodes() {
  const src = readSource(STATES_DIR, "deep.ts");
  const block = src.slice(src.indexOf("DEEP_PACKS: DeepPack[] = ["));
  return [...block.matchAll(/\{\s*meta:\s*([A-Z]{2})_META/g)].map((m) => m[1]);
}

/** Pull one string field out of a program literal (handles wrapped lines). */
function field(chunk, name) {
  const m = chunk.match(new RegExp(`^    ${name}:\\s*\\n?\\s*"((?:[^"\\\\]|\\\\.)*)"`, "m"));
  return m ? m[1].replace(/\\"/g, '"') : "";
}

/** Read a source file with line endings normalised — the repo has a mix of
 *  LF and CRLF, and every pattern below assumes LF. */
function readSource(...parts) {
  return readFileSync(join(...parts), "utf8").replace(/\r\n/g, "\n");
}

function parsePack(code) {
  const src = readSource(STATES_DIR, code, "programs.ts");
  const nameMatch = readSource(STATES_DIR, code, "meta.ts").match(/name:\s*"([^"]+)"/);
  return {
    code,
    name: nameMatch ? nameMatch[1] : code,
    programs: src
      .split("\n  {\n")
      .slice(1)
      .map((chunk) => ({
        id: field(chunk, "id"),
        name: field(chunk, "name"),
        category: field(chunk, "category"),
        agency: field(chunk, "agencyName"),
        source: field(chunk, "sourceUrl"),
        lastVerified: field(chunk, "lastVerified"),
        volatile: field(chunk, "volatile"),
      }))
      .filter((p) => p.id),
  };
}

function render(packs) {
  const out = [];
  const totalPrograms = packs.reduce((n, p) => n + p.programs.length, 0);

  out.push("## **11\\. State Program Packs (audit trail)**");
  out.push("");
  out.push(
    `*Generated by \`npm run audit:sources\` from \`src/data/states/**\` — ` +
      `${packs.length} states, ${totalPrograms} state-administered programs. Do not hand-edit.*`
  );
  out.push("");
  out.push(
    "Every program below is encoded as data in `src/data/states/<CODE>/programs.ts` and was read " +
      "off the linked official page on its `last_verified` date. A state reaches **FULL COVERAGE** " +
      "only when its pack carries at least 8 verified state-administered programs, always covering " +
      "food, health, energy and cash (SNAP, Medicaid/CHIP, LIHEAP, TANF) — enforced by " +
      "`tests/unit/coverage-bar.test.ts`. Re-verify before relying on any figure."
  );
  out.push("");

  for (const pack of packs) {
    const categories = new Set(pack.programs.map((p) => p.category));
    out.push(
      `### **${pack.name} (${pack.code})** — ${pack.programs.length} programs, ` +
        `${categories.size} categories`
    );
    out.push("");
    out.push("| Program | Category | Administering agency | Official source | last_verified |");
    out.push("| ----- | ----- | ----- | ----- | ----- |");
    for (const p of pack.programs) {
      out.push(
        `| ${p.name} | ${CATEGORY_LABEL[p.category] ?? p.category} | ${p.agency} | ` +
          `${p.source} | ${p.lastVerified} |`
      );
    }
    out.push("");
  }

  // Derived watch list — one row per program carrying a `volatile` note.
  const volatile = packs.flatMap((pack) =>
    pack.programs.filter((p) => p.volatile).map((p) => ({ ...p, state: pack.code }))
  );
  out.push("### **Volatile — re-check before each release**");
  out.push("");
  if (volatile.length === 0) {
    out.push("*No program currently carries a `volatile` note.*");
  } else {
    out.push(
      "*Derived from the `volatile` field on each program, so the warning lives next to the " +
        "figure it describes rather than in a list that can drift.*"
    );
    out.push("");
    out.push("| Program | State | What's moving |");
    out.push("| ----- | ----- | ----- |");
    for (const p of volatile) {
      out.push(`| ${p.name} | ${p.state} | ${p.volatile} |`);
    }
  }
  out.push("");
  return out.join("\n");
}

const codes = deepStateCodes();
const packs = codes.map(parsePack);
const section = render(packs);

let doc = readFileSync(DOC, "utf8");
const startIdx = doc.indexOf(START);
const endIdx = doc.indexOf(END);

if (startIdx !== -1 && endIdx !== -1) {
  doc = doc.slice(0, startIdx) + START + "\n\n" + section + "\n" + doc.slice(endIdx);
} else {
  throw new Error(
    `Markers not found in ${DOC}. Add the following pair where the section should live:\n` +
      `${START}\n${END}`
  );
}

writeFileSync(DOC, doc, "utf8");
console.log(
  `audit:sources — wrote ${packs.length} state tables ` +
    `(${packs.reduce((n, p) => n + p.programs.length, 0)} programs, ` +
    `${packs.flatMap((p) => p.programs.filter((x) => x.volatile)).length} volatile) to ${DOC}`
);
